apiVersion: v1
kind: Service
metadata:
  name: gitdeployment
  namespace: namespace-workflow-1742208965546
  labels:
    app.kubernetes.io/name: gitdeployment
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: gitdeployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80